image: node:18-alpine

stages:
  - build
  - deploy

variables:
  DEPLOY_DIR: /var/www/pcpartsearcher # Deployment directory on your server

build-website:
  stage: build
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/dist/


deploy-website:
  stage: deploy
  image: alpine/git:latest
  script:
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "mkdir -p $DEPLOY_DIR && rm -rf $DEPLOY_DIR/*"
    - scp -r -o StrictHostKeyChecking=no client/dist/* $SSH_USER@$SERVER_IP:$DEPLOY_DIR
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "systemctl restart nginx"
  only:
    - main