image: node:18-alpine

stages:
  - test
  - build
  - deploy

variables:
  DEPLOY_DIR: /var/www/pcpartsearcher
  API_DEPLOY_DIR: /var/www/pcpartsearcher-api

# Frontend jobs
frontend-test:
  stage: test
  image: node:18-alpine
  cache:
    key:
      files:
        - client/package-lock.json
    paths:
      - client/node_modules
  script:
    - cd client
    - npm ci
    - npm run lint
    - npm run tsc

frontend-build:
  stage: build
  image: node:18-alpine
  cache:
    key:
      files:
        - client/package-lock.json
    paths:
      - client/node_modules
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    paths:
      - client/dist/

# Backend jobs
backend-test:
  stage: test
  image: python:3.12-slim
  cache:
    key:
      files:
        - server/requirements.txt
    paths:
      - .pip-cache/
  variables:
    PIP_CACHE_DIR: .pip-cache/
  script:
    - cd server
    - pip install -r requirements.txt
    - python -m pytest tests/ || echo "No tests found"

backend-build:
  stage: build
  image: python:3.12-slim
  script:
    - cd server
    - pip install -r requirements.txt
  artifacts:
    paths:
      - server/

# Deployment jobs
deploy-frontend:
  stage: deploy
  image: alpine:latest
  needs:
    - frontend-build
  script:
    - apk add --no-cache openssh-client sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "mkdir -p $DEPLOY_DIR"
    - sshpass -p "$SSH_PASSWORD" scp -r -o StrictHostKeyChecking=no client/dist/* root@$SERVER_IP:$DEPLOY_DIR
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "command -v nginx >/dev/null 2>&1 || yum install -y nginx"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl restart nginx"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "curl -f http://localhost || exit 1"
  only:
    - main

deploy-backend:
  stage: deploy
  image: alpine:latest
  needs:
    - backend-build
  script:
    - apk add --no-cache openssh-client sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "mkdir -p $API_DEPLOY_DIR"
    - sshpass -p "$SSH_PASSWORD" scp -r -o StrictHostKeyChecking=no server/* root@$SERVER_IP:$API_DEPLOY_DIR
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "command -v python3 >/dev/null 2>&1 || yum install -y python3"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "command -v pip3 >/dev/null 2>&1 || python3 -m ensurepip"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "yum install -y gcc python3-devel"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "cd $API_DEPLOY_DIR && pip3 install -r requirements.txt"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "echo '[Unit]
Description=PcPartSearcher API
After=network.target

[Service]
User=root
WorkingDirectory=$API_DEPLOY_DIR
ExecStart=/usr/bin/python3 $API_DEPLOY_DIR/run.py
Restart=always

[Install]
WantedBy=multi-user.target' > /etc/systemd/system/pcpartsearcher-api.service"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl daemon-reload"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl enable pcpartsearcher-api"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "systemctl start pcpartsearcher-api"
    - sleep 5
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@$SERVER_IP "curl -f http://localhost:8000/health || exit 1"
  only:
    - main