services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - FLASK_ENV=production
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
    networks:
      - app-network

networks:
  app-network:
    driver: bridge