version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app
      - ./scrapers:/app/scrapers
    environment:
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge